# Taskfile.yaml
version: "3"

vars:
  ROOT_COMPOSE: docker compose -f stack.yml # root-level compose
  ROLE_COMPOSE: docker compose -f ansible/roles/pocket_lab/files/stack.yml
  PLAYBOOK: ansible/site.yml
  INVENTORY: ansible/inventory/hosts.yml

tasks:

  init-env:
    desc: "Create .env from template (for manual compose)"
    cmds:
    - test -f .env || cp .env.template .env

  up:
    desc: "Start stack (root-level compose + .env)"
    cmds:
    - task:init-env
    - "{{.ROOT_COMPOSE}} pull"
    - "{{.ROOT_COMPOSE}} up -d"

  down:
    desc: "Stop & remove containers (root compose)"
    cmds: [ "{{.ROOT_COMPOSE}} down -v --remove-orphans" ]

  logs:
    desc: "Tail logs (root compose)"
    cmds: [ "{{.ROOT_COMPOSE}} logs -f --tail=100" ]

  restart:
    desc: "Restart one service – usage: task restart -- n8n"
    cmds: [ "{{.ROOT_COMPOSE}} restart {{.CLI_ARGS}}" ]

  prune:
    desc: "Docker system prune"
    cmds: [ "docker system prune -f" ]

  ansible-deploy:
    desc: "Run Ansible playbook (pass extra args via -- …)"
    cmds:
    - ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}} {{.CLI_ARGS}}

  ansible-check:
    desc: "Dry-run Ansible"
    cmds:
    - ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}} --check {{.CLI_ARGS}}
