stack_state: present
# ---------- Paths / versions ----------
docker_version: "latest"
docker_compose_version: "v2.36.0"
compose_repo: "/opt/pocket_lab"

# ---------- DNS ----------
cloudflare_api_token: ""

# ---------- Stack-wide ----------
stack_domain: "ai.lab.example.com"
stack_email: "admin@example.com"
stack_timezone: "Europe/Berlin"
mem_limit: "4g"
traefik_version: "v3.4.1"

# ---------- Auth ----------
# create with:  htpasswd -nbB user "yourpassword"
# Current set Defaults - User: admin | Password: admin
basic_auth: 'admin:$2y$05$F6KSt6mnvnqqPhQ3VTLIAugnQuhhtJAhdi09Qf0oxBysbbZacqbXK'


# ───── Observability  ────
prometheus_version: "v3.3.1"
loki_version: "3.0.0"
grafana_version: "10.4.3"
grafana_admin_user: "admin"
grafana_admin_password: "admin"
node_exporter_version: "v1.9.1"
portainer_version: "2.20.3"
portainer_port: "9000"

# ---------- n8n ----------
n8n_version: "1.50.0"
webhook_url: "https://n8n.{{ stack_domain }}/"
n8n_host: "n8n.{{ stack_domain }}"
n8n_protocol: "https"
n8n_editor_base_url: "https://n8n.{{ stack_domain }}/"
n8n_admin_email: "admin@example.com"
n8n_admin_password: "changeme"
n8n_basic_auth_active: false
n8n_personalization_enabled: false
n8n_diagnostics_enabled: false
n8n_version_notifications_enabled: false
n8n_templates_enabled: false

# ---------- ollama ----------
ollama_version: "0.10.0"
ollama_pull_models: "llama3.1:8b deepseek-r1:7b qwen2.5-coder:7b bge-m3"
ollama_mmap: true
ollama_max_replicas: 4
ollama_idle_timeout: 120s
ollama_num_parallel: 8
ollama_context_size: 4096
ollama_keep_alive: 5m
ollama_max_loaded_models: 3
ollama_max_queue: 512


# ---------- openwebui ----------
openwebui_version: "v0.6.22"
openwebui_port: "8080"
openwebui_admin_email: "admin@example.com"
openwebui_admin_password: "changeme"
openwebui_enable_signup: false
openwebui_default_user_role: "pending"
openwebui_enable_persistent_config: true
# ---------- openwebui: endpoints & web search ----------
# Derived URL used by Open WebUI for building absolute links (set in template)
webui_url: ""
openwebui_offline_mode: false
openwebui_enable_version_update_check: false
openwebui_enable_web_search: true
openwebui_web_search_engine: "searxng"
openwebui_enable_search_query_generation: true
openwebui_web_search_result_count: 5
openwebui_web_search_concurrent_requests: 2
searxng_query_url: "http://searxng:8080/search?q=<query>&format=json"
ollama_base_url: "http://ollama:11434"
openwebui_default_models: "llama3.1:8b deepseek-r1:7b qwen2.5-coder:7b"
openwebui_default_prompt_suggestions:
  - { title: "Code review",        content: "Review the following code and point out bugs, security issues, and style problems." }
  - { title: "Explain a snippet",  content: "Explain what this code does and how to improve it." }
  - { title: "Research topic",     content: "Summarize recent developments on <topic> with citations and links." }
  - { title: "Write tests",        content: "Generate unit tests for this function with edge cases." }


# ----------  Elasticsearch ----------
es_version: "8.13.4"
es_port: 9200
es_password: "changeme"
es_host: "es01"

# -------- infinity -----------
infinity_version: "v0.6.0-dev3"
infinity_thrift_port: 23817
infinity_http_port: 23820
infinity_psql_port: 15432
infinity_host: "infinity"

# ----------- mysql -----------
mysql_version: "8.0.39"
mysql_root_password: "changeme"
mysql_port: 3306
mysql_host: "mysql"
mysql_dbname: "pocket_lab"


# --------- minio -------------
minio_version: "RELEASE.2025-04-22T22-12-26Z"
minio_port: 9000
minio_console_port: 9001
minio_root_user: "minioadmin"
minio_root_password: "minioadmin"

# ---------- valkye/redis ----------
redis_version: "8.1.0"
redis_password: "changeme"
redis_port: 6379
redis_host: "redis"


# ---------- stirling pdf ----------
stirling_pdf_version: "latest"
stirling_pdf_port: "8080"
stirling_pdf_enable_login: false

# ---------- rerank tei ----------
tei_version: "cpu-1.8"


# -------------- ragflow ------------
svr_http_port: 9380

hf_endpoint: "https://huggingface.co"
macos: false
ragflow_doc_engine: "elasticsearch"
ragflow_version: "v0.18.0"
ragflow_extra_ports: "9382"
ragflow_nginx_conf_dir: "./ragflow/nginx"
ragflow_history_dir: "./ragflow/history_data_agent"
ragflow_log_dir: "./ragflow/ragflow-logs"

register_enabled: 0
ragflow_admin_email: "admin@ragflow.io"
ragflow_admin_password: "changeme"

llm_factory: "Ollama"
llm_api_key: ""
llm_api_base: "http://ollama:11434"
llm_chat_model: "llama3.1:8b"
llm_embedding_model: "bge-m3"
llm_rerank_model: "onnx-community/bge-reranker-v2-m3-ONNX"
llm_asr_model: ""
llm_image2text_model: ""

# ---------- no-code architects toolkit ----------
nca_toolkit_version: "latest"
nca_api_key: "replace_me"
nca_s3_endpoint: "http://minio:{{ minio_port }}"
nca_s3_bucket: "pocket-lab"
nca_s3_access_key: "{{ minio_root_user }}"
nca_s3_secret_key: "{{ minio_root_password }}"

# ---------- Tailscale ----------
ts_authkey: ""
docker_bridge_subnet: "172.20.0.0/16"

# ---------- smtp relay ----------
smtp_image: "boky/postfix:latest"
smtp_host: "smtp"
smtp_port: 25
smtp_ssl: false

