- name: Harden & prepare the server
  hosts: genai_servers
  become: true
  remote_user: "{{ l3d_users__local_users[0].name }}"

  pre_tasks:
  - name: Ensure privilege‑separation dir exists
    file:
      path: "{{ sshd_priv_separation_path | default('/run/sshd') }}"
      state: directory
      owner: root
      group: root
      mode: "0755"

  roles:
  - devsec.hardening.os_hardening
  - role: devsec.hardening.ssh_hardening
    vars:
      ssh_permit_root_login: "no"
      ssh_allow_users: "{{ users_user_list | map(attribute='name') | join(' ') }}"
  - role: geerlingguy.docker
    vars:
      docker_install_compose: true
