- name: Deploy the Pocket‑Lab stack
  hosts: genai_servers
  become: true
  gather_facts: false          # we’ll gather after user is fixed
  pre_tasks:
    - name: Ensure connection user is known (probe if cache expired)
      include_role:
        name: ensure_conn_user
      # delegate_to: localhost

    - name: Use that user for the rest of the play
      set_fact:
        ansible_user: "{{ conn_user }}"
    - meta: reset_connection

    - name: Gather facts as {{ ansible_user }}
      setup:

  roles:
    - pocket_lab
    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
