# ansible/roles/ensure_conn_user/tasks/main.yaml
- block:

  - set_fact: { conn_user: '' }

  - name: Probe candidate users
    include_tasks: probe_user.yaml
    loop: "{{ probe_list | unique | difference(['']) }}"
    loop_control: { loop_var: candidate }

  - assert:
      that: conn_user | length > 0
      fail_msg: "No SSH login worked for {{ inventory_hostname }}"

  # make it persistent (24 h cache timeout set in ansible.cfg)
  - name: Set connection user fact
    set_fact:
      conn_user: "{{ conn_user }}"
      cacheable: yes
  when: hostvars[inventory_hostname].conn_user is not defined
