# ansible/roles/ensure_conn_user/tasks/probe_user.yaml

- name: Test {{ candidate }}@{{ inventory_hostname }}
  delegate_to: localhost
  become: false
  vars:
    probe_addr: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"

    # --- collect connection settings from inventory -------------------------
    ssh_key: >-
      {{ hostvars[inventory_hostname].ansible_ssh_private_key_file
           | default(hostvars[inventory_hostname].ansible_private_key_file
           | default('')) }}
    ssh_port: "{{ hostvars[inventory_hostname].ansible_port | default('') }}"
    ssh_extra: "{{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}"
  shell: |
    ssh -o BatchMode=yes                        \
        -o ConnectTimeout=5                     \
        -o PreferredAuthentications=publickey   \
        -o IdentitiesOnly=yes                   \
        -o StrictHostKeyChecking=no             \
        {% if ssh_port|length %}-p {{ ssh_port }}{% endif %} \
        {% if ssh_key|length  %}-i {{ ssh_key  }}{% endif %} \
        {{ ssh_extra }}                         \
        {{ candidate }}@{{ probe_addr }} "exit 0"
  register: ssh_test
  failed_when: false
  changed_when: false
  when: conn_user == ""

- set_fact:
    conn_user: "{{ candidate }}"
  when: conn_user == "" and ssh_test.rc == 0 # succeed only on rc=0
