- name: Create compose directory
  file:
    path: "{{ compose_repo }}"
    state: directory
    mode: '0755'

- name: Copy entire stack asset tree (preserve perms)
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ compose_repo }}/"
    mode: preserve

- name: Render .env file
  template:
    src: .env.j2
    dest: "{{ compose_repo }}/.env"
    mode: "0640"

- name: Render traefik_dynamic.yaml file
  template:
    src: traefik_dynamic.yaml.j2
    dest: "{{ compose_repo }}/traefik/traefik_dynamic.yaml"
    mode: "0640"

- name: Launch stack
  community.docker.docker_compose_v2:
    project_src: "{{ compose_repo }}"
    check_files_existing: false
    pull: missing
    state: present
    files:
    - compose.yaml
