- name: Create compose directory
  file:
    path: "{{ compose_repo }}"
    state: directory
    mode: '0755'

- name: Copy entire stack asset tree (preserve perms)
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ compose_repo }}/"
    mode: preserve

- name: Render .env file
  template:
    src: .env.j2
    dest: "{{ compose_repo }}/.env"
    mode: "0640"

- name: Ensure acme.json exists with 0600
  copy:
    content: "" # create empty file if absent
    dest: "{{ compose_repo }}/traefik/acme.json"
    mode: "0600"

- name: Launch stack
  community.docker.docker_compose_v2:
    project_src: "{{ compose_repo }}"
    check_files_existing: false
    pull: missing
    state: present
    files:
    - stack.yaml
