- name: Install Docker engine
  shell: |
    curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Install Docker Compose plugin
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'

- name: Ensure user is in docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Enable & start Docker
  service:
    name: docker
    state: started
    enabled: yes
