- name: Install base packages
  ansible.builtin.package:
    name: "{{ _base_pkgs[ansible_os_family] | default(_base_pkgs['Fallback']) }}"
    state: present
  vars:
    _base_pkgs:
      Debian: [ curl, gnupg, ca-certificates, ufw ]
      RedHat: [ curl, yum-utils, firewalld ]
      Suse: [ curl, firewalld ]
      Archlinux: [ curl, ufw ]
      Fallback: [ curl ]

- name: Ensure vm.max_map_count is 262144 (persistent)
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: true
