---
- name: Bootstrap users
  hosts: genai_servers
  become: true
  gather_facts: false
  roles:
    - l3d.users.user
    - l3d.users.admin

- name: Harden & prepare the server
  hosts: genai_servers
  become: true
  roles:
    - devsec.hardening.os_hardening
    - role: devsec.hardening.ssh_hardening
      vars:
        ssh_permit_root_login: "no"
        ssh_allow_users: "{{ users_user_list | map(attribute='name') | join(' ') }}"
    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
- name: Deploy the poket lab stack
  gather_facts: false
  hosts: genai_servers
  become: true
  roles:
    - pocket_lab